CREATE TABLE "applications" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"submittedAt" text,
	"name" text,
	"prefName" text,
	"school" text,
	"grade" text,
	"email" text,
	"instagram" text,
	"discord" text,
	"oneLine" text,
	"teamsRanked" text,
	"flexible" text,
	"why" text,
	"pushback" text,
	"hours" text,
	"webProject" text,
	"stack" text,
	"portfolioUrl" text,
	"accountUrl" text,
	"wrongWithEvent" text,
	"coldEmail" text,
	"room4y" text,
	"anything" text,
	"referrer" text
);
